### ISSUE TITLE
git repository size analysis

### ISSUE THREAD

**Issue by DentonGentry** [ProjectDrawdown/solutions#1]
Early in the project, we checked in a bit over 100 Excel files of several megabytes each. Though now deleted from the active tree, these files make the repository object store very large at almost a gigabyte in size.

We have an opportunity to do something about this in a planned move from gitlab to github: we could rewrite the git history to, for example, use LFS for the large file storage. However, attempts to migrate to LFS have not appreciably reduced the size of the .git directory and we don't understand why.

Investigating what can be done about this while we have the opportunity to do so would be helpful. The largest blobs in the object store are:

$ git rev-list --objects --all | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' | sed -n 's/^blob //p' | sort --numeric-sort --key=2 | cut -c 1-12,41- | tail -20

```
fe1b0e183fea 6791894 ddexcel_models/SolarPVUtility_RRS_ELECGEN_v1.1d_27Aug18_VBAWEB.xlsm
6ac53e49b5ce 6792020 ddexcel_models/SolarPVUtility_RRS_ELECGEN_v1.1d_27Aug18_VBAWEB.xlsm
6a3fe5f79031 6800320 ddexcel_models/SolarPVUtility_RRS_ELECGEN_v1.1d_27Aug18_VBAWEB.xlsm
671ff3cc7a89 6800710 ddexcel_models/SolarPVUtility_RRS_ELECGEN_v1.1d_27Aug18_VBAWEB.xlsm
3bad310c00a3 6801652 ddexcel_models/SolarPVUtility_RRS_ELECGEN_v1.1d_27Aug18_VBAWEB.xlsm
8705e5fa274e 6825137 solution/landfillmethane/testdata/LandfillMethane_RRS_ELECGEN_v1.1c_24Oct18.xlsm
0c08fe1b0c0e 6891454 solution/telepresence/testdata/Drawdown-Videoconferencing and Telepresence_RRS_v1.1_17Dec2018_PUBLIC.xlsm
714850cac92d 6903351 solution/telepresence/testdata/Drawdown-Videoconferencing and Telepresence_RRS_v1.1_17Dec2018_PUBLIC.xlsm
520ab6d62582 6982795 solution/offshorewind/testdata/Drawdown-Wind Offshore_RRS.ES_v1.1_13Jan2019_PUBLIC.xlsm
102f6ba87359 6995400 solution/offshorewind/testdata/Drawdown-Wind Offshore_RRS.ES_v1.1_13Jan2019_PUBLIC.xlsm
dda05ad28868 6996617 solution/offshorewind/testdata/Drawdown-Wind Offshore_RRS.ES_v1.1_13Jan2019_PUBLIC.xlsm
2d9f7eaaa0d5 7208602 solution/concentratedsolar/testdata/CSP_RRS_ELECGEN_v1.1b_24Oct18.xlsm
02ee2a4e31c7 7706040 solution/onshorewind/testdata/Drawdown-Onshore Wind_RRS.ES_v1.1_13Jan2019_PUBLIC.xlsm
271c9223c28a 7706149 solution/onshorewind/testdata/Drawdown-Onshore Wind_RRS.ES_v1.1_13Jan2019_PUBLIC.xlsm
adbccc9b8818 7718159 solution/onshorewind/testdata/Drawdown-Onshore Wind_RRS.ES_v1.1_13Jan2019_PUBLIC.xlsm
d293fe0074e7 7719422 solution/onshorewind/testdata/Drawdown-Onshore Wind_RRS.ES_v1.1_13Jan2019_PUBLIC.xlsm
40723a19c5a4 8119873 solution/solarpvutil/testdata/SolarPVUtility_RRS_ELECGEN_v1.1b_2Nov2019.xlsm
41b719868925 8897359 solution/wastetoenergy/testdata/old/WastetoEnergy_RRS_ELECGEN_v1.1b_24Oct18.xlsm
048a8aba91be 13948030 solution/walkablecities/testdata/Drawdown-Walkable Cities_RRS_v1,1_31Dec2018_PUBLIC.xlsm
937eb043e50c 13959716 solution/walkablecities/testdata/Drawdown-Walkable Cities_RRS_v1,1_31Dec2018_PUBLIC.xlsm
```

We tried using git lfs migrate.

Before doing anything:
$ cd .git
$ du -sk *
967300	objects
(no change after git gc)

Running LFS migrate:

$ git lfs migrate import --include="*.xlsx" --include="*.xlsm" --include-ref=refs/heads/master
$ git reflog expire --expire-unreachable=now --all
$ git gc --prune=now

$ du -sk *
1086664	lfs
967928	objects

I understand why there is now an lfs directory: that caches the LFS objects we just created, and if we were to push this tree to an upstream, anyone cloning it would not download those objects because they are not active at HEAD. I believe there are two copies of the objects in there, so we have ~500 MBytes of LFS files taking up ~1000 MBytes of disk space.

I don't understand why the objects directory is still the same size. It seems like it should be ~500 MBytes smaller.

**Comment by DentonGentry** [comment]
Resolved by @apenwarr: https://twitter.com/apenwarr/status/1219744205070852103

make a new directory
git init
git fetch <orig git client>

$ du -sk .git/*
115120	.git/objects

down from 967928.

**Comment by apenwarr** [comment]
:)
