### ISSUE TITLE
Create TopoJSON files from spatial-aez data

### ISSUE THREAD

**Issue by DentonGentry** [ProjectDrawdown/solutions#108]
data/world_topo_sans_antartica_highres.json is a [TopoJSON](https://github.com/topojson/topojson) file encoding the Project Drawdown regions: OECD90, Eastern Europe, Asia (Sans Japan), Middle East and Africa, Latin America, plus China, India, EU, and USA. It is used with [Altair charts](https://altair-viz.github.io/gallery/world_projections.html) for map projections in the Jupyter Notebook researcher UI.

data/world_topo_with_aez.json was intended to be used for Land solutions, but the AEZ regions it contains do not match the Project Drawdown AEZ definitions closely enough so was not used. It is also so large as to be unwieldy.

### spatial-aez
_Boreal Forest:_ grows in cold environments at high latitudes, in permafrost / mostly frozen soil.
_Temperate Forest:_ grows in warmer climates, though cooler than Tropical forests.

Data sources used by Project Drawdown through most of its development did not provide enough granularity to distinguish km² of each, so the two were combined as Temperate/Boreal and the total land area used. This was unfortunate as some solutions are more appropriate for Temperate or for Boreal, but the model had to use the total area of both.

In late 2019 we decided to address this by analyzing satellite imagery to produce the specific data result for what the project needed. This effort was based off of the scripts in tools/topo which produced data/world_topo_sans_antartica_highres.json. The processing was further refined in a [spatial-aez](https://github.com/ProjectDrawdown/spatial-aez), a separate git repository within this same project.

The data on land area produced by [spatial-aez](https://github.com/ProjectDrawdown/spatial-aez) is now being used in Drawdown land solution models.

### [TopoJSON](https://github.com/topojson/topojson) from [spatial-aez](https://github.com/ProjectDrawdown/spatial-aez)
There would be two parts to this effort:
1. The Natural Earth shapefile in [spatial-aez](https://github.com/ProjectDrawdown/spatial-aez) can be processed into a [TopoJSON](https://github.com/topojson/topojson) file to replace data/world_topo_sans_antartica_highres.json. This would be beneficial because there have been a few land transfers and disputed regions which we should be consistent between land area and displayed maps. For example, a substantial arctic boundary dispute between Norway and Russia was resolved in 2010.
1. The TMR+AEZ GeoTIFF images can be processed into a file to use in Land solutions as data/world_topo_with_aez.json was intended for but never used. This could be implemented as a new geo chart in the TLA and AEZ tabs of the Researcher UI.

This is marked as a good-first-issue because it would not require coming up to speed on the rest of the solution models, but it would require coming up to speed on [TopoJSON](https://github.com/topojson/topojson) and geospatial processing tools like [GDAL](https://gdal.org/).

**Comment by olehb** [comment]
PR for part 1 of this task: https://github.com/ProjectDrawdown/solutions/pull/163

**Comment by uklineale** [comment]
Hi, is this issue still open? I saw that this PR got merged: https://github.com/ProjectDrawdown/solutions/pull/173

**Comment by DentonGentry** [comment]
PR 173 did not finish this implementation, however since this issue was opened almost a year ago, the UI has undergone substantial change. I do not believe the TopoJSON files would be useful in the current iteration of the UI.
