### ISSUE TITLE
pytest to show DeprecationWarnings in our own code

### ISSUE THREAD

**Issue by DentonGentry** [ProjectDrawdown/solutions#11]
We began running pytest -W ignore::DeprecationWarning, as hundreds of deprecation warnings from site-packages were overwhelming. Unfortunately this has concealed a number of deprecation warnings in code which we do actively develop, such as things which break in [Pandas 1.0 (see issue #4)](https://github.com/ProjectDrawdown/solutions/issues/4).

This seems like a problem which should have a solution, to restrict pytest warnings to local code and ignore site-packages.

**Comment by avishayp** [comment]
The straightforward way is to use `-W once::DeprecationWarning`
It brings #warnings down to 27 on the "not slow" suite.

**Comment by DentonGentry** [comment]
That does reduce the number of warnings, but isn't quite what I had in mind: it would happily print the first deprecation warning it sees in site-packages, and then suppress all of the cases of that warning in our own code.

What I'd really like is for it to print every deprecation warning in the code where we are likely to fix deprecation warnings. I'm happy to clean up stuff within the codebase.

As it is, those very helpful deprecation warnings from the code we would be happy to fix are drowned out by deprecation warnings from installed python packages that we're not going to do anything about. Those are the ones I'd like to suppress, the warnings on code which is someone else's problem.
