### ISSUE TITLE
UI for multiple solutions

### ISSUE THREAD

**Issue by DentonGentry** [ProjectDrawdown/solutions#12]
A primary goal for this software development is to provide a new suite of tools for Project Drawdown to use in its outreach efforts. We need to build tools which will leverage the solution models and allow exploration, creation of visualizations and media for presentations and outreach, and other uses.

We refer to an interactive UI covering all Drawdown solutions as the Gallery UI, which has a separate [Drawdown Solutions UI: Gallery View](https://docs.google.com/document/d/1LJFkVSbFUkYxG7kDV7GQjwx0sDKa97N1LS4zkLrfm2A/edit) document, which is mostly a survey of similar efforts in this space.

**Comment by DentonGentry** [comment]
Some updated thoughts and plans of how we might go about providing one or more user interfaces into the results of the solution models are in: https://docs.google.com/document/d/1yZr1n63tDNZ4YI_sAmzvf3QITidJeuCvqAEyTcbKxKA/comment

**Comment by DentonGentry** [comment]
There is a mockup of a user interface in https://github.com/ProjectDrawdown/explorer, and running as a hosted instance on https://solutions.geekhold.com/services/explorer/

It is based on Drawdown Interactive, as described in the [Gallery UI document](https://docs.google.com/document/d/1LJFkVSbFUkYxG7kDV7GQjwx0sDKa97N1LS4zkLrfm2A/edit#heading=h.o3u0qwdm1e7k).

The mockup uses UI elements developed earlier for the Researcher UI. Most of them use [Vega](https://vega.github.io/), so the JSON Vega description is checked in to https://solutions.geekhold.com/services/explorer/ to serve using Tornado.

**Comment by jamescrowley** [comment]
@DentonGentry would this incorporate something like that referenced in https://github.com/ProjectDrawdown/solutions/issues/110 too, or is that tangential to this?

**Comment by DentonGentry** [comment]
Noting here: issue #110 concerns a dashboard about the state of the solution models, intended for use by the research team and software developers. A version of the ModelHealth dashboard exists but has to be run locally as a Jupyter notebook, which is not very approachable and makes it impossible to (for example) put a link to it in an email or presentation. Issue #110 tracks re-implementation of the ModelHealth dashboard in some sort of online form, like generating Github Pages.

This issue is a user interface and visualization for an audience which is not likely to be as concerned about the deep intricacies of the model, and more concerned about making plans for what they should do. As some examples:

- I have a municipal budget of N for a city at location Y, what solutions should I focus on for investigating how to allocate that budget?
- I am an individual in country A, what choices can I make with an impact?
- my supply chain is mostly located in region Z, what might I consider in RFPs if I want to start greening my supply chain?

I don't expect the ModelHealth dashboard would appear in this UI, I think those are distinct audiences.

**Comment by jamescrowley** [comment]
@DentonGentry I guess you saw my comment before I removed it, as I came to realise these were indeed serving different audiences! Thanks for clarifying.

**Comment by DentonGentry** [comment]
Obsolete.
