### ISSUE TITLE
UI for Researcher use

### ISSUE THREAD

**Issue by DentonGentry** [ProjectDrawdown/solutions#13]
Currently the project has a UI focussed on deeper analysis of a single solution, currently hosted in a Jupyter Notebook via a JupyterHub instance running in the cloud. Alternatives to Jupyter in a native JavaScript framework could also be considered.

## Overview
This issue covers one user interface into the new system, an Analyst View whose purpose is to provide a deep view into the scenarios and allow different starting assumptions to be modeled and compared. The intended audience will be sophisticated and relatively knowledgeable about what they are trying to accomplish using the tools:
+ Researchers, both Drawdown Fellows and third parties wanting to work with the Drawdown models.
+ Policy Analysts from government or business, looking to inform Deciders or provide supporting information for a decision.

## Guiding Principles
There are a set of guidelines for the Analyst View:
+ The Drawdown models are constructed using the Python programming language. Knowledge of Python should not be required to use the Analyst View, however we have no reason to hide the existence of Python and allow interaction more directly with the models. Exposing Python for use will be valuable for the (substantial) fraction of this audience who are familiar with it.
+ A portion of this audience will interact with the UI for an extended period of time, perhaps months on a regular basis. The UI should avoid techniques which become tedious upon extended use. For example while the Gallery View may animate transitions, the Analyst View should have transitions which are smoothed but quick.

## Options Considered
For data science projects in Python there are a number of options, but two particularly stand out: Jupyter Notebook and Tableau. Both were investigated but the project initially settled on Jupyter, for two main reasons:
1. A free software (AGPL) implementation has been a goal from the beginning of the project, and Jupyter is able to support that goal.
1. The Tableau pricing model does not fit well with the plan to allow widespread use by outside researchers and analysts.

### Multiple Solutions + Multiple Scenarios
The intention of the Analyst View is to primarily focus on a portion of the Drawdown solution space, either because one is directly working on those models (or the data sources driving them) or because different options are being compared. The intention of the Analyst View is not to focus on broad surveys of a large number of solutions.

The Analyst View should focus on supporting a small number of solutions simultaneously, each with one or more scenarios loaded. The Analyst View should continue to function even as larger numbers of solutions are loaded, but the UI affordances do not need to be aimed at large numbers of simultaneous comparisons.
<img width="519" alt="charts" src="https://user-images.githubusercontent.com/1140756/74107349-aefd5d00-4b23-11ea-8800-a447250f00e9.png">

### Define New Scenarios
This is considered a high priority requirement by the project: the UI should provide a way to define a new scenario, meaning a new set of initial assumptions and parameters, and allow the model to compute the results.

## Jupyterhub prototype
An initial iteration of the Analyst UI has been constructed using Jupyter, via both Jupyterlab and Voila. There is a walkthrough and getting started guide available at https://youtube.com/watch?v=MMrQwObdEZ4, and the system can be tried out at https://solutions.geekhold.com.
<img width="469" alt="jupyterhub" src="https://user-images.githubusercontent.com/1140756/74107357-cf2d1c00-4b23-11ea-9064-196dd926aa70.png">

**Comment by sanbornhilland** [comment]
This might be something I could contribute to but I need a bit of help wrapping my head around what is needed. Could you answer a few questions to get the ball rolling?

1. This is marked as "high priority" but there's been no movement on it. Do you still consider it high priority?
1. @DentonGentry mentioned there are pros and cons to sticking with Jupyter. Could you provide a bit of detail on that and whether you're leaning one way or the other. 
1. Do you have a good idea of what the next steps should be? This ticket provides a very high level picture, which is useful but it's hard to contribute to without some more specifics.

**Comment by DentonGentry** [comment]
1. I do consider it a high priority, the velocity of development is due more than anything to the small set of people working on the project (roughly, 1 person until quite recently). 
  
1. I think there are a few pros of Jupyter:  
    + the target user is a climate researcher interested in further work on one or more of the solution models. This person is, more than likely, a grad student, postdoc, or early career academic. Familiarity with Jupyter is fairly widespread in this audience, I've seen estimates of 40-50%.
    + Jupyter has a notion of a frontend talking to backend kernels, which provides most of the glue to let the Python model code running in a kernel talk to a frontend.
    + JupyterHub (hosting service) provides a user login with a local directory, which matches well with the idea for researcher workflow. The hope is for researchers to use git: make changes in the data files, bundle it into a git commit, submit it for review. We might have this in a UI where you don't have to know that it uses git, but within the system it is git.
  
    However there are also a number of cons to Jupyter:
    + JupyterLab's sandboxing model for JavaScript makes it very hard to incorporate existing JavaScript libraries. D3, CesiumPy, etc would be useful but not easy to incorporate, a jupyter labextension must be developed for each.
    + Jupyter's UI widget library, ipywidgets, is pretty limited.

1. For next steps: if we keep using Jupyter, I think a good next step would be to write out files. The current system running on https://solutions.geekhold.com/ will allow changes to be made in a number of UI elements and has Save/Abandon buttons, but they don't do anything. That is where work left off in the last big push.

**Comment by DentonGentry** [comment]
Some updated thoughts and plans of how we might go about providing one or more user interfaces into the results of the solution models are in: https://docs.google.com/document/d/1yZr1n63tDNZ4YI_sAmzvf3QITidJeuCvqAEyTcbKxKA/comment

**Comment by DentonGentry** [comment]
Obsolete.
