### ISSUE TITLE
Implement 8 Thermal Moisture Regimes

### ISSUE THREAD

**Issue by DentonGentry** [ProjectDrawdown/solutions#18]
Thermal Moisture Regimes (TMRs) are a classification based on the combination of average temperature and rainfall. Until late 2019, Project Drawdown used six Thermal Moisture Regimes: Tropical-Humid, Tropical-Semiarid, Temperate/Boreal-Humid, Temperate/Boreal-Semiarid, Arctic, and Arid. The research team had long wanted to separate Temperate from Boreal, as the two have different sets of solutions which are applicable, but were basing the land area classifications on papers and data sources which did not provide enough information to separate the two.

In late 2019 as a part of this Python development effort, we [developed code to process satellite imagery](https://github.com/ProjectDrawdown/spatial-aez) for land cover, soil health, slope, and other factors and allow Project Drawdown to produce its own classifications of land area. This allowed an expansion to 8 TMRs, with Temperate and Boreal having separate Humid and Semiarid classes.

The 2020 versions of the Excel models are being updated to use 8 TMRs, but the current Python model is based on the 2019 Excel files which have 6 TMRs. The Python code will need to be updated to handle the new TMR definitions.

**Comment by martin-laurent** [comment]
Hi @DentonGentry I'm willing to work on this task. Based on your knowledge of the code base, what are the main components that are affected by this change?

**Comment by DentonGentry** [comment]
The 6 thermal moisture regimes currently implemented are defined in model/dd.py:
```
 # Land
 THERMAL_MOISTURE_REGIMES = ['Tropical-Humid', 'Temperate/Boreal-Humid', 'Tropical-Semi-Arid',
                             'Temperate/Boreal-Semi-Arid', 'Global Arid', 'Global Arctic']
```

The recent change in the Excel models is to separate Temperate from Boreal, so we will have:

```
 # Land
 THERMAL_MOISTURE_REGIMES = ['Tropical-Humid', 'Temperate-Humid', 'Boreal-Humid',
                             'Tropical-Semi-Arid', 'Temperate-Semi-Arid',
                             'Boreal-Semi-Arid', 'Global Arid', 'Global Arctic']
```

I'm not sure this will impact the rest of the code in model/*.py very much, the places which use dd.THERMAL_MOISTURE_REGIMES tend to do so in a loop and don't make assumptions about how many TMRs there will be.

Where it will have an impact is:
+ data/land/allocation/ has directories for each TMR, six right now, containing CSV files for each Agro-Ecological Zone within that Thermal Moisture Regime. This will need to be expanded to eight directories for eight TMRs. The CSV files in those directories were extracted from the Land solution Excel files; the 2020 version of those Excel files can be extracted again and will have eight TMRs.
+ Determine if we can simultaneously support some solutions using six TMRs and some using eight. If not, we'd have to update *all* of the Land solutions to the 2020 versions simultaneously with adding support for the new Thermal Moisture Regimes.

To be honest: I'm not sure this is a good first project. Some of the other issues are marked as a good first issue.

**Comment by DentonGentry** [comment]
An update about timing, all at the time of this writing 3/2020:
- the cohort2018 solution models were developed by the cohort of researchers who worked on the project in 2018. These were used as the basis for the Python implementation hosted here, the Python solutions implement the cohort2018 models.
- the cohort2019 solution models are those used to provide data for publication of [The Drawdown Review](https://www.drawdown.org/) in March 2020. We are currently updating the Python implementations to match cohort2019. At this moment the energy models have been updated and we're starting on the Land Use models. Notably, the cohort2019 models still use six Thermal Moisture Regimes; Temperate and Boreal are still combined together, as they were in cohort2018.
- the work to separate Temperate and Boreal is happening now in the Excel implementation, and is expected in the cohort2020 models.

So the effort to implement 8 TMRs can wait a bit, we're only just beginning to get updated solutions using 8 TMRs.
