### ISSUE TITLE
Food Waste & Plant Rich Diet

### ISSUE THREAD

**Issue by DentonGentry** [ProjectDrawdown/solutions#22]
There are a few solutions where the Excel implementation has yet to be implemented in Python. [Food Waste](https://www.drawdown.org/solutions/food/reduced-food-waste) and [Plant Rich Diet](https://www.drawdown.org/solutions/food/plant-rich-diet) are two such solutions, where the Excel model differs substantially from most of the other solutions. It will take a separate effort to implement these in Python.

Most of the existing ~70 Python solutions were constructed by building the modules used in the model methodology, but then creating the individual solutions using a code generator. The code generator is not expected to be useful for [Food Waste](https://www.drawdown.org/solutions/food/reduced-food-waste), [Plant Rich Diet](https://www.drawdown.org/solutions/food/plant-rich-diet), and similar solutions, as there are too few of them to make such automation worthwhile.

**Comment by uklineale** [comment]
Is this something a non climate scientist could take a stab at?

**Comment by DentonGentry** [comment]
Likely. There is a hackathon being organized in March which might be an opportunity to look into it. If interested, you can reach out to alden at pragmatical dot org.

**Comment by uklineale** [comment]
Great. I just signed up on the form and will message alden. Thank you.

**Comment by denised** [comment]
I'm going to close this issue since we'll be re-opening a bunch of new issues with respect to missing models, and I want to split this into two separate issues.
