### ISSUE TITLE
Make the data open

### ISSUE THREAD

**Issue by rufuspollock** [ProjectDrawdown/solutions#235]
This is an *amazing* project - wonderful to see.

You license the code under an open license, yay and thank-you! 👏 

Could you do the same for the data and release is under and [open license](https://opendefinition.org/)? E.g. one of the Open Data Commons license https://opendatacommons.org/ or an open Creative Commons license (e.g. public domain, share-alike etc)?

I ask as you currently use a closed license because of the non-commercial restriction:

> Data supplied from Project Drawdown (mostly in the form of CSV files) is licensed under the **CC-BY-NC-2.0** license for non-commercial use. The code for the model can be used (under the terms of the AGPL) to process whatever data the user wishes under whatever license the data carries. The data supplied for the Project Drawdown solutions is CC-BY-NC-2.0.

For more on why using an Open Definition compatible license (for data) matters see https://blog.okfn.org/2014/09/30/why-the-open-definition-matters-for-open-data-quality-compatibility-and-simplicity/

**Comment by denised** [comment]
@rufuspollock --- Thank you for your interest.  I will forward this request, but my understanding is that the current licensing is required of us by some of the sources of the data --- that is we are using data that comes to us under licensing restrictions already.

**Comment by rufuspollock** [comment]
@denised could you provide a bit of info given you just closed the issue. If some of the data is restricted that does not require restricting all the data ...
