### ISSUE TITLE
Python Architecture Diagram

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#249]
Problem: The current architecture in python cannot **update the variables and see an impact**. This is the critical architecture needed. The architecture design needs to be reviewed and re-structured. 

Description: Creation of a architecture diagram. 

Acceptance criteria: 
- Architecture supports the unused variables that are needed
https://docs.google.com/spreadsheets/d/1UyDXHyItk0aN36Q7w6oHkXHQI4t9FLxZhvAFD2aDymg/edit?pli=1#gid=697424438
- users must be able to update variables and see updates to their solution sets. 
- developers can run chain through new architecture and evaluate work remaining. 
- Developers can use this architectural diagram to support their implementation of remaining models (supporting open source community ongoing). 

Question: How can we present this architecture in a digestable way for the client/ stakeholders to review and approve.

**Comment by denised** [comment]
I've removed the documentation label since I think that should be reserved for documentation that is intended to be published with the code.  The intention of this document (in my view) is just to get us devs on the same page about a few things and to work out some preliminary design.

**Comment by denised** [comment]
This is related to a bunch of upcoming work with colab (https://github.com/ProjectDrawdown/global-research-platform/issues/56, https://github.com/ProjectDrawdown/global-research-platform/issues/5, etc.).

**Comment by denised** [comment]
I believe this document is no longer relevant.  Closing.
