### ISSUE TITLE
Create Technical Specification Document

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#253]
Need: Technical specification Document should show how does the python code work to deliver that functionality. 

Description: The person review this will be knowledgable about climate and models who will be executing the code. However, how much will the understand about what the code is doing? 

We may need a technical writer to help with this. 

See notes on the topic here: https://github.com/ProjectDrawdown/global-research-platform-web-ui/wiki/PDD-One-Project-Weekly-Notes-6-14-to--6-18-2021

**Comment by glass-wing** [comment]
Technical specification takes the form of type annotations and doc strings. These have now been added to the ocean sector models.
