### ISSUE TITLE
Add Functional requirements document to the documentation suite in github

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#255]
Need: Functional requirements document which describes functionality within the system 

This should already be done, and can be shared with us by the PDD team.

Acceptance criteria: This documentation has been added to the github documentaiton suite and can be used by developers to understand the system

Note: This also needs to be accessible within the Open Collaboratory.

**Comment by denised** [comment]
I don't believe we need to have a Functional Requirements document, per se.  What we do need is user documentation.  Can you change the title to reflect that?

**Comment by denised** [comment]
...And since you have another issue open for that, I'm going to close this as not required.
