### ISSUE TITLE
Assessing completeness of existing models

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#256]
Problem: There is a need for clarity regarding how complete existing models are.

Background: Our understanding is that Denton left many models 70% complete.  

Desired outcome: time estimate for incomplete models.

**Comment by DentonGentry** [comment]
From https://projectdrawdown.github.io/solutions/ :
- 47 of the solutions are implemented in Python based on the Excel 3/2020 release (for The Drawdown Review)
- 23 of the solutions are implemented in Python based on the Excel 1/2019 release (the "public" release with an AGPL license, later withdrawn)
- 9 of the solutions are not implemented in Python. These are mostly the ones which differ more substantially from the RRS and Land models, like Food Waste and the Health solutions.

Of the solutions implemented in Python, I didn't have more on the list of things that were needed. It is not the case that each of them individually is 70% done, it is that overall 47 of the 70 were completely done, 23 of the 70 were pretty far along but needed to be updated, and 9 of the 70 have a lot left to be done.

I'm sure even those 47 will need additional changes for however you proceed.

----

Aside: the code that generates https://projectdrawdown.github.io/solutions/ was in the dashboard directory, which I note has been moved to limbo/dashboard and the workflow has been removed.

**Comment by colleenskemp** [comment]
This is hugely helpful @DentonGentry! Thank you so much!

**Comment by denised** [comment]
I am closing this issue in its current form as essentially completed.  Denton's notes above, and our own discussions with Chad, have confirmed that there are no major areas of missing core calculations that are needed for this python-push project.  Any core calculation items that might be discovered will be treated as bugs.  At some point we will have a push to add "additional variables" and secondary calculations; I will make another issue specifically for that.
