### ISSUE TITLE
Jupyter notebook oriented towards developers

### ISSUE THREAD

**Issue by denised** [ProjectDrawdown/solutions#262]
Create a notebook that leads a developer through the process of instantiating solutions & scenarios and accessing and visualizing the results.   

Bonus: notebook also introduces tools that are available.

This should form a significant part of the required documentation for the project.

**Comment by denised** [comment]
I have an initial version for this, but I think others do as well.  Should collect best ideas.

**Comment by denised** [comment]
Expanding on such notebook might be a good hackathon candidate

**Comment by colleenskemp** [comment]
This is a task folks can contribute to as they are looking at other things. Everyone is encouraged to work on this.

**Comment by denised** [comment]
We have the "Start Here" notebook as a prototype of this.  It will continue to be enhanced, but no longer needs a separate work item for it.
