### ISSUE TITLE
Inventory of tools already in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#263]
Chad is requesting clarity on which tools that are already built in python. 

Some tools are already in Python, for example - in adoption. See notes here: https://github.com/ProjectDrawdown/global-research-platform-web-ui/wiki/PDD-One-Project-Weekly-Notes-6-27-to-7-2-2021

**Comment by denised** [comment]
Did a first cut; asked @chadfrisch for review
