### ISSUE TITLE
Integrations design: updating downstream models to upstream changes

### ISSUE THREAD

**Issue by denised** [ProjectDrawdown/solutions#265]
One type of integration summarizes upstream model effects on downstream inputs, e.g. updating the TAM.
We want a standard way to describe how this will work that can be re-used across all such integrations, including the API pattern, how data is found and where it is written to.

If we can complete this pre-hackathon, it might enable implementation of integrations as a hackathon activity.

**Comment by denise-alter-ego** [comment]
Hey, can I help out?

**Comment by denised** [comment]
Completed with PR #440
