### ISSUE TITLE
Implement High Performance Glass (Commercial) in Python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#270]
Problem: This solution is currently missing from the python code and needs to be added. 

Current excel: Glass_RRS_Model_Commercial-Nov19	

Sector: Building	

Category: RSS		

Acceptance criteria: Researchers can use python to run this model just as they are able to do in the excel version.

**Comment by babablacksheep** [comment]
Hi - Kunal Joshi and Angel have been assigned this task

**Comment by babablacksheep** [comment]
(I am Kunal Joshi. Sorry the username doesn't make it obvious)

**Comment by AngelCarballoCremades** [comment]
I will be working on this issue :)

**Comment by babablacksheep** [comment]
I see that another person Anagha Uppal has also been assigned here.

**Comment by anaavu** [comment]
I'll be working on this

**Comment by denised** [comment]
@johnpaulalex is working on this

**Comment by johnpaulalex** [comment]
yup working on this!

**Comment by denised** [comment]
Completed in #455
