### ISSUE TITLE
Complete High Performance Glass (Residential) Model

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#271]
The initial model has been imported but is failing tests.  The task is now to fix and complete the model.

**Comment by colleenskemp** [comment]
@denised - my understanding is that you are using this one as a dry run prep for the hackathon. Is that right?

**Comment by denised** [comment]
Correct.  I will be back to working on it today.

-- 
  Denise Draper
  ***@***.***

**Comment by denised** [comment]
I've spent multiple days on this one.  At this point, I am working on a test failure in HelperTables:
````
AssertionError: Solution: High-Performance Glass (Residential) Scenario: PDS1-73p2050-2.75% Retrofit Rate (Integrated) Helper Tables B91:C137
DataFrames differ:
Err [0][1] : '32513.13214817388' != '32762.74892'
Err [1][1] : '32877.61758792763' != '33060.56169'
Err [2][1] : '33239.49189861846' != '33358.37446'
Err [3][1] : '33598.43656012793' != '33656.18723'
````

These are the data for `scenobj.ht.soln_ref_funits_adopted()['World']` for the years 2014-2017.  The fact that the errors are only
in the first years indicates that it is an issue with how adoption is overridden for years before the base year of 2018.

**Comment by denised** [comment]
A baseline version of this model (still not working) has been checked in to develop in PR #375.  Anybody who wants to work on it, should start from there.

**Comment by denised** [comment]
Completed in PR #386 (finally)
