### ISSUE TITLE
Complete Household and Commercial Recycling Model

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#272]
The initial model import has been done, but it is failing tests.  This task is now to fix the failures and complete the model
An NDA is required to access the Excel spreadsheet required.

**Comment by dbeef** [comment]
Working on the issue.

**Comment by alienau8** [comment]
Also working on this issue

**Comment by gupabhi** [comment]
I am also working on this issue.

**Comment by alexlod** [comment]
I'm working on this as well.

**Comment by Carson-Poe** [comment]
I am working on this also.

**Comment by alexlod** [comment]
Here's a WIP PR many of us have been working on: https://github.com/ProjectDrawdown/solutions/pull/353
