### ISSUE TITLE
Implement Improve Aquaculture solution in  python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#274]
Problem: This solution is currently missing from the python code and needs to be added.

Excel: Improve aquaculture_March2021.xlsm	

Sector: Ocean	

Category: Fishery & Aquaculture	

Acceptance criteria: Researchers can use python to run this model just as they are able to do in the excel version

**Comment by glass-wing** [comment]
Implemented. Uses new unit test class "test_ocean_improve_solution.py"
