### ISSUE TITLE
Implement Improve Fishery Biomass solution in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#275]
Problem: This solution is currently missing from the python code and needs to be added.

Current Excel: Improve Fishery_Fish biomass_March2021.xlsm	

Sector: Ocean	

Category: Fishery & Aquaculture	

Acceptance criteria: Researchers can use python to run this model just as they are able to do in the excel version

**Comment by glass-wing** [comment]
Implemented.
