### ISSUE TITLE
Implement Protect Coastal Wetlands (Seagrasses) solution in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#278]
Problem: This solution is currently missing from the python code and needs to be added.

Current Excel: Drawdown_RRS-BIOSEQProtect_Model_v1.1b_Coastal_Wetlands(Seagrasses)_Jun2020.xlsm	

Sector: Ocean	

Category: Protection & Restoration	

Acceptance criteria: Researchers can use python to run this model just as they are able to do in the excel version

**Comment by glass-wing** [comment]
Implemented - all tests working.
