### ISSUE TITLE
Implement Protect Macroalgae solution in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#279]
Problem: This solution is currently missing from the python code and needs to be added.

Current excel: Macroalgae protection_Ocean Model_March2021.xlsm	

Sector: Ocean	

Category: Protection & Restoration	

Acceptance criteria: Researchers can use python to run this model just as they are able to do in the excel version

**Comment by glass-wing** [comment]
Finished implementation on glass-wing fork.
