### ISSUE TITLE
Implement Restore Macroalgae solution in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#281]
Problem: This solution is currently missing from the python code and needs to be added.

Current Excel: Macroalgae Restoration_Ocean Model_Mar2021.xlsm	

Sector: Ocean	

Category: Protection & Restoration	

Acceptance criteria: Researchers can use python to run this model just as they are able to do in the excel version

**Comment by glass-wing** [comment]
Finished implementation on glass-wing fork.
