### ISSUE TITLE
Implement Seaweed Farming solution in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#284]
Problem: This solution is currently missing from the python code and needs to be added.

Current Excel: Seaweed_Farming-FINAL_for_review_March2021.xlsm	

Sector: Ocean	

Category: Fishery & Aquaculture	

Acceptance criteria: Researchers can use python to run this model just as they are able to do in the excel version

**Comment by glass-wing** [comment]
Finished implementation on glass-wing fork.
