### ISSUE TITLE
NEW MODEL - Implement Recycled Plastic solution in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#287]

**Comment by cathbar** [comment]
You can assign this to me.

**Comment by everAspiring** [comment]
Working on this

**Comment by denised** [comment]
This is now checked in to develop in PR #375.   I'm sorry but I couldn't find any way to keep your names on the commit, so in the end I just had to copy files over.   But you have the credit of the first working new model in over a year!!  Many thanks
