### ISSUE TITLE
NEW MODEL - Implement Recycled Metals solution in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#288]
See `Extraction_Guide.md` in the Documentation folder for how to get started

**Comment by Sunishchal** [comment]
Ajay Anand & Wayland Lee have claimed this ticket

**Comment by denised** [comment]
It turns out we jumped the gun on this one.  There is not enough data yet to make this into a real model, so we will not be converting it yet.

**Comment by denised** [comment]
Whoops, wrong one!  It is recycled glass that is not a model yet!

**Comment by denised** [comment]
Completed with PR #398
