### ISSUE TITLE
Complete Methane Leak Management Model

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#290]
See `Extraction_Guide.md` in the Documentation folder for how to get started

**Comment by anshulgoyal10** [comment]
I'm working on this issue.

**Comment by msa856** [comment]
as am I

**Comment by anshulgoyal10** [comment]
Current excel: Oil and gas methane management model

Sector: Avoided Methane

**Comment by anshulgoyal10** [comment]
Blocking Issue: excel file has no stored scenarios in the `ScenarioRecord` tab.

**Comment by denised** [comment]
The lack of scenarios has been fixed.  This task is no longer blocked.

**Comment by denised** [comment]
Completed with commit 8f176b84bc
