### ISSUE TITLE
NEW MODEL - Implement Improved Manure Management in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#291]

**Comment by AndreasVermeulen** [comment]
Hi, Andreas Vermeulen and Ali-Hamzah Ahmed is working on this for July 2021 - Hackathon

**Comment by AndreasVermeulen** [comment]
Found several errors in Excel files that makes the conversions fail.
Still busy debugging the excel formats.

Will book fixed excel files with code to compare later.

**Comment by denised** [comment]
Completed.
