### ISSUE TITLE
Make solution testing less monolithic

### ISSUE THREAD

**Issue by denised** [ProjectDrawdown/solutions#296]
The solution testing system we have now (see file `tests/test_excel_integraton.py`) has a few shortcomings that impair its usefulness:
1. Many dozens of individual tests are performed per solution, but the way the code is written these are aggregated into a giant list and executed all at once.  This has two downsides:
    1. A solution either passes or fails as a unit.  The first failure stops the test of that solution.  It would be very helpful to perform all the tests and see individually which pass and which fail.
    1. When failure is signaled, the execution context in which it was produced is already gone.  This makes debugging more challenging, compared to being able to drop into a debugger at the time of failure.
2. The test code is currently separated from the solutions.   This makes it difficult for developer working on a solution to have partial or customized testing for their own solution without changing the centralized test structure (which is  scary piece of code).  It would be better to use class inheritance in such a way that standard tests are shared across most solutions, but can be overridden within each solution directory.  This should have the added benefit of giving developers more visibility into the testing and encourage them to actually use it.

I have a prototype of a solution that meets these requirements published on repo [denised/solutions](https://github.com/denised/solutions/tree/test_prototype), branch test-prototype.  The overall structure is in place, but there is a fairly massive effort required to translate the existing tests, and update the solutions to use them.

Please contact @denised if you would like to help with this effort.  It may make sense to do the initial work on this off of my repo before pushing it to Project Drawdown --- that way even partial progress can be usefully included.

Familiarity with pytest (or desire to learn it) are useful for this task.

**Comment by johnpaulalex** [comment]
I can work on this.

**Comment by denised** [comment]
Thank you @johnpaulalex

**Comment by denised** [comment]
Closing this as not a current priority.  While it would be nice to refactor the tests so that they ran more granularly, most of what we needed has been accomplished by other means.
