### ISSUE TITLE
Create Documentation supporting testing suite 

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#297]
There are tests in a testing suite. Don't want to add more tests to the system. 

Documentation needs to be added that tells you how to run it.

**Comment by colleenskemp** [comment]
Could making these tests be good hackathon work?

**Comment by DentonGentry** [comment]
Other than, or instead of, https://github.com/ProjectDrawdown/solutions/blob/develop/tests/test_excel_integration.py ?
