### ISSUE TITLE
Evaluate completeness and accuracy of existing models

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#299]
Relates to this spreadsheet: https://docs.google.com/spreadsheets/d/1UyDXHyItk0aN36Q7w6oHkXHQI4t9FLxZhvAFD2aDymg/edit#gid=1443595911

Request for Denise: Provide results from existing python models for three key results: 
1) cumulative emissions
2) net first cost
3) net lifetime operational savings

From here @Chad can review the results, compare with excel results, and identify remaining needs for completing these solutions on Python

**Comment by denised** [comment]
Completed.  The results are available at on the google drive at [key_results_sample.July12.csv](https://drive.google.com/file/d/1-3bPB9sLU7bUEUMRCBk06O1O3TL-EO4k/view?usp=sharing), and have been shared with Chad and Mamta
