### ISSUE TITLE
XLS files in tam.py, adoptiondata.py, customadoption.py

### ISSUE THREAD

**Issue by DentonGentry** [ProjectDrawdown/solutions#3]
[model/tam.py](https://github.com/ProjectDrawdown/solutions/blob/master/model/tam.py), [model/adoptiondata.py](https://github.com/ProjectDrawdown/solutions/blob/master/model/adoptiondata.py), and [model/customadoption.py](https://github.com/ProjectDrawdown/solutions/blob/master/model/customadoption.py) read in CSV files of market size and adoption data. The existing CSV files were produced via the [vma_xls_extract.py](https://github.com/ProjectDrawdown/solutions/blob/master/tools/vma_xls_extract.py) code generator from the original Drawdown Excel models.

This issue concerns adding support for XLS files for researcher convenience.

The desired steps are:
1. In \_\_init\_\_ of each of those classes, check the file extension of the data source and add support for *.xlsx and *.xlsm

1. Add unit tests to model/tests. Add an Excel file for use in the test in model/tests/data.

1. Please use Pandas read_excel() and ensure it works with the 'xlrd' backend, as we already have dependencies on xlrd in the tree. We do not currently have any dependencies on other Excel+python packages like openpyxl, and would prefer not to add new dependencies without a really good reason.

**Comment by DentonGentry** [comment]
It would be great if a single Excel file for a solution could supply VMA (issue #2), customadoption/adoptiondata/etc (issue #3), plus allow additional sheets for various and sundry stuff specific to the solution which doesn't benefit from being done within Python.

A way to do this would be to check if sheets named "TAM" or "TAM Data", "Adoption Data", "Custom PDS Adoption", and "Custom REF Adoption" exist and use them if they do.

**Comment by FranzEricSchneider** [comment]
I'll take a crack at this, should be faster after going through #2

**Comment by DentonGentry** [comment]
A few notes of things which have come up since the original issue was written up:

- Adoption Data and TAM should be doable. The relevant portions of the sheets are usually manually entered data from a source paper or study, and we could make model/adoptiondata.py and model/tam.py be able to read in XLS in addition to CSV.
- Custom PDS Adoption/Custom REF Adoption is maybe not doable the way I thought. The Land models make most use of Custom {PDS|REF} Adoption, and they often work by referencing cells from other parts of the model like Unit Adoption or TLA to use those to compute an adoption curve. The code generator would extract the final adoption curve and turn it into a CSV file, but this wasn't great as it became totally static and lost the original intention of the researcher.  
    
    The Excel models were updated for a new release in 3/2020 of The Drawdown Review, and we're gradually converting the updated models to Python. I've been doing manual work to convert the Custom {PDS|REF} Adoption to an equivalent computed representation, for example in [Managed Grazing starting at line 150](https://github.com/ProjectDrawdown/solutions/blob/3989b514c97fa806460a5e31a993dfd08dda1b76/solution/managedgrazing/__init__.py#L150)

So I'd recommend starting with Adoption Data and TAM Data, and customadoption should wait until later.

Additionally, regarding the amount of time to open a workbook: I'd expect we'd check in one XLSX file in solution/name/name.xlsx, and it would have Sheets for Variable Meta-Analysis, Adoption Data, and TAM Data. You might consider encapsulating xlrd.open_workbook() in a class, and using model/metaclass_cache.py for it. model/tam.py is an existing example of using metaclass_cache.

A design principle since early on has been that classes take their inputs in their \_\_init\_\_ method and not later after construction, allowing the metaclass_cache to be used if the object is expensive to create. The same object is returned for the same arguments.

In that way, the first VMA/adoptiondata/tam to open the Excel file would pay the cost of opening the workbook, and then subsequent uses would be much faster.

**Comment by FranzEricSchneider** [comment]
Sounds good. I was looking to use the existing `sivopasture.xslx` test file, and just expand it for this, but I found something odd. The original/full silvopasture xlsm file doesn't include a TAM sheet, though it does have AdoptionData. The other three xlsm files that I spot-checked have both. Is something wrong with the silvopasture file, or is this sheet optional?

**Comment by DentonGentry** [comment]
Silvopasture is a Land solution, which uses the TLA (Total Land Area) sheet for its adoption limits. I don't think there is much value in adding XLS handling for TLA: the amount of land area on the planet is effectively a constant, erosion and deposition are not large enough to be material to the results. Since a human researcher isn't likely to be adjusting the TLA, it isn't as important to preserve things like columns widths and colors and so on.

To get a TAM Data sheet it will need to be an RRS (Reduction and Replacement Solution) file. We typically use Solar Farms for this, just because it was the first solution we started working with. There is a tools/tests/solarpvutil_vma.xlsm file in the repository already, though it looks like we removed the TAM Data sheet from it before checking it in.

I'd recommend using tools/tests/solarpvutil_vma.xlsm but adding TAM Data back in, from the original XLSM files that I think you got via "git revert" if I'm remembering correctly.

**Comment by FranzEricSchneider** [comment]
In the full solarpvutil xlsm file I see "Adoption Data" and "TAM Data" sheets, but I also see "Fresh Adoption Data" and "Fresh TAM Data" sheets. What's the relationship there?

**Comment by DentonGentry** [comment]
I think the Fresh versions of the sheets can be ignored.

The Adoption Data and TAM Data sheets are formatted to hold 11 data sources maximum. The spreadsheets were already rearranged once, they originally held 8 sources.

When 11 sources wasn't enough for this year's research work, the person working on the energy solutions didn't want to deal with rearranging the spreadsheet again and made a copy of the sheets instead. The older sources to replicate the results from the 2017 book were relegated to a different sheet, while current sources are in Adoption Data and TAM Data.

Only the sources on Adoption Data and TAM Data actually work, to run the older results requires renaming sheets to move the older sources into place.

This is really a sign of having outgrown Excel as a tool, more than anything.
