### ISSUE TITLE
User spec for what the integrations should look like to a developer

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#300]
Problem: These won't look the same for a coding dev than they currently look in excel. There is a design step needed. This should be collaborative between dev team and Chad/ Mamta. 

Find details regarding integrations and integration steps/ process here: https://docs.google.com/spreadsheets/d/1UyDXHyItk0aN36Q7w6oHkXHQI4t9FLxZhvAFD2aDymg/edit#gid=1443595911

**Comment by colleenskemp** [comment]
This is going to have to follow the hackathon. Will be needed prior to defining integration tickets.

**Comment by denised** [comment]
I think this can be closed as a separate ticket.  I have a pretty good understanding of how I think the integrations should be implemented, which I have reviewed with Chad and Mamta.  There will undoubtedly be changes as we get more deeply involved, but I don't expect to spend any more time on design as an independent project.
