### ISSUE TITLE
Add utility tools to python for "Inflation Adjustment Factor" tool

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#323]
Need: Implement Inflation adjustment factor tool into python (this is one of the common conversions).

To find  Inflation adjustment factor table and formulas:

Go to the VMA tab for any solution.
Scroll to the right.
See it to the right of Energy Conversions
Example: In solution "BiomassPower_RRS_ELECGEN_26June2020" Energy conversions can be found starting in cell Z2.

Acceptance criteria:
Utility function that will do the inflation adjustment factor calculations.

**Comment by denised** [comment]
Including in "conversion functions" ticket.
