### ISSUE TITLE
Add utility function for "Carbon to CO2 Conversions" tool in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#329]
Need: Implement Carbon to CO2 Conversions tool into python (this is one of the common conversions).

To find Carbon to CO2 Conversions table and formulas:

Go to the VMA tab for any solution.
Scroll to the right.
Third tool in the third column
Example: In solution "BiomassPower_RRS_ELECGEN_26June2020" Energy conversions can be found starting in cell AJ30.

Acceptance criteria:
Utility function that will do the Carbon to CO2 Conversions calculations.

**Comment by denised** [comment]
Already implemented
