### ISSUE TITLE
Add utility function for "GHG to CO2-eq  Conversions" tool in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#330]
Need: Implement "GHG to CO2-eq  Conversions" tool into python (this is one of the common conversions).

To find "GHG to CO2-eq  Conversions" table and formulas:
Go to the VMA tab for any solution.
Scroll to the right.
Last table in the third column of common conversions
Example: In solution "BiomassPower_RRS_ELECGEN_26June2020" Energy conversions can be found starting in cell AJ37.

Acceptance criteria:
Utility function that will do the"GHG to CO2-eq  Conversions" calculations.

**Comment by denised** [comment]
already implemented
