### ISSUE TITLE
As a user, I can indicate source validation using python model

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#331]
Need: Able to indicate source validation in python model. 

To find source validation table:
Go to the VMA tab for any solution.
Scroll to the right.
Find this to the right of common conversions
Example: In solution "BiomassPower_RRS_ELECGEN_26June2020" Energy conversions can be found starting in cell AQ2.

Acceptance criteria:
As a user, I can indicate source validation out of the options below

1  - Peer Reviewed
2 - Public Sector/ Multilateral Agency
3 - For Profit
4 - Independently Verified
5 - Not Verified

**Comment by denised** [comment]
This is a table of codes that may be used in a VMA table.  The VMA tables already have these codes embedded in them.
