### ISSUE TITLE
Add utility function for S-Curve adoption tool in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#333]
Need: Implement S-Curve adoption tool into python 

Description:
To find S-Curve adoption table and formulas:
Find S-Curve adoption tab in any solution 

- Much of this we already have the calculations in python. Some of this IS implemented. 
- To do the Bass Diffusion Model, you need to use the Solver function in excel. 

Acceptance criteria:
Utility function that will do the S-Curve adoption calculations.

**Comment by colleenskemp** [comment]
This is an important tool and should be prioritized.

**Comment by denised** [comment]
What is not yet implemented is a user interface that allows users to visually choose between different parameterized curves.  It would be interesting to experiment with doing something like this in jupyter notebook.
