### ISSUE TITLE
Add function for "Estimate Future Prices for Technology" in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#335]
Need: Implement "Estimate future prices for technology" into python 

To find Estimate future prices for technology table and formulas:
Go to the VMA tab for any solution.
Scroll almost to the bottom
Example: In solution "BiomassPower_RRS_ELECGEN_26June2020" Energy conversions can be found starting in cell A1756.

Acceptance criteria:
Utility function that will do the Esimtate future prices for technology calculations.

**Comment by colleenskemp** [comment]
As a helpful next step - could @chadfrisch or @MamtaMehra do a walk-through of how to use this tool. That would be very helpful.

**Comment by denised** [comment]
This is part of the "Learning Rate" tool
