### ISSUE TITLE
Add utility function for "Adoption Data" tool in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#336]
Need: Implement Adoption data tool into python

To find Adoption data table and formulas:
Find Adoption data tab in any solution. 
See example here: https://drive.google.com/file/d/1IOxQoFlkIfkJOjEwSLGraArLnCuY48yn/view?usp=sharing

Acceptance criteria:
Utility function that will do the adoption data calculations.

**Comment by colleenskemp** [comment]
This is an important tool and should be prioritized.

**Comment by denised** [comment]
This exists already
