### ISSUE TITLE
Add utility function for TAM data tool in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#337]
Need: Implement TAM data tool into python

To find TAM data table and formulas:
Find TAM data tab in any solution.
See example here: https://drive.google.com/file/d/1IOxQoFlkIfkJOjEwSLGraArLnCuY48yn/view?usp=sharing

Acceptance criteria:
Utility function that will do the TAM data calculations.

**Comment by colleenskemp** [comment]
This is an important tool and should be prioritized.

**Comment by denised** [comment]
This exists already
