### ISSUE TITLE
Add utility function for "Scenario Record" tool in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#338]
Need: Implement Scenario Record tool into python

To find Scenario Record table and formulas:
Find Scenario Record tab in any solution.
See example here: https://drive.google.com/file/d/1IOxQoFlkIfkJOjEwSLGraArLnCuY48yn/view?usp=sharing

Acceptance criteria:
Utility function that will do the Scenario Record calculations.

**Comment by colleenskemp** [comment]
This tool is of high importance!

**Comment by denised** [comment]
This is implemented in a different way in the python code already.  There is a related issue already (#258) that addresses a missing bit of functionality.
