### ISSUE TITLE
Add utility function for Custom PDS adoption tool in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#340]
Need: Implement Custom PDS adoption tool into python

To find Custom PDS adoption table and formulas:
Find Custom PDS adoption tab in any solution.
See example here: https://drive.google.com/file/d/1IOxQoFlkIfkJOjEwSLGraArLnCuY48yn/view?usp=sharing

Acceptance criteria:
Utility function that will do the Custom PDS adoption calculations.

**Comment by denised** [comment]
The core functionality already exists in the code
