### ISSUE TITLE
Add utility function for custom ref adoption tool in python

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#341]
Need: Implement custom ref adoption tool into python

To find custom ref adoption table and formulas:
Find custom ref adoption tab in any solution.
See example here: https://drive.google.com/file/d/1IOxQoFlkIfkJOjEwSLGraArLnCuY48yn/view?usp=sharing

Acceptance criteria:
Utility function that will do the custom ref adoption calculations.

**Comment by denised** [comment]
The core functionality already exists in the python code.
