### ISSUE TITLE
Add utility conversions package.

### ISSUE THREAD

**Issue by denised** [ProjectDrawdown/solutions#347]
This is a simple one :-)
On the Variable Meta-Analysis tab of any model, to the right starting at column P, are a series of tables expressing useful conversions.  In python we would like to have a utility module that would calculate these conversions, which could then be used in other calculations.  There are a couple of factors (`rrs.TERRAWATT_TO_KILOWATT` and `land.MHA_TO_HA`) that are expressed as constants, but we'd like to migrate these to functions (`def terrawatt_to_kilowatt(tw)`), put them in a single shared conversion module, and add the others found on the VMA tab:
* energy conversions
* volume conversions
* mass conversions
* distance conversions
* land area conversions
* inflation-adjusted-dollars

Note: CO2 and CO2-eq conversions are already implemented elsewhere.

**Comment by ssmssam** [comment]
Hey, 
Is something like this what you are looking for https://github.com/ssmssam/solutions/blob/adding_utilitiies_module/model/conversions.py   

There are two functions replacing the rss and land constants, and have refactored the code to call these functions now instead. 

I've also created an energyConversion class, which has a lookup dictionary of the values from the first row and column in that table on the excel file. I used both the row and column to keep decimal rounding errors to a minimum so it could more closely replicate the values found in that excel sheet. 

The conversions are not always identical , e.g. in the code 1 twh = 859,845.2292000001 gcal
                                                                                in excel 1 twh = 859,845.228000 gcal 

If this is useful, I can generalise the class and make a metaclass which all the conversion classes will inherit from. Would just need to change; self.conversion_rates, self._base_name, self.accepted_names for each class

**Comment by denised** [comment]
This looks really good @ssmssam --- I'll look into it in more detail as soon as I get a chance!

**Comment by denised** [comment]
Sam I really like this approach --- much nicer than making tons of functions for every possible energy conversion, and leaves open the possibility of extensions later.
The metaclass approach should make the code very clean too.

Please continue!

**Comment by ssmssam** [comment]
Great thank you :). I thought it might end up being a bit easier to use rather than having to look through all the functions to see which one is there. 
I will add unit tests then refactor to get the metaclass. Hope to be done with it all by end of tomorrow if that's ok.

**Comment by ssmssam** [comment]
All done :)

**Comment by denised** [comment]
Excellent work --- thank you!
