### ISSUE TITLE
Complete Peatlands Restoration Model

### ISSUE THREAD

**Issue by denised** [ProjectDrawdown/solutions#351]
The initial model import has been done, but tests are failing.  The task is to complete this work.
Note: an NDA is required to access the Excel model for comparison

**Comment by denised** [comment]
I've been working on this one.   I've run into these issues so far:
* I needed to add a line to data/land/aez/solution_aez_matrix.csv for this solution.  I copied the line for the other peatlands solution, assuming it would be the same.
 * UTF failure because of special characters in the description of the first custom adoption (hacked around by deleting those characters from __init__.py)
 * Test failure in `verify_aez_data` that looks like a numerical issue (hacked around by commenting out that test)
 * Test failure in `verify_custom_adoption` (1).   The extraction code is assuming that a custom adoption has a fixed set of sources with fixed 'include' parameters (`"Custom Ref Adoption"!S25:S34`).  In peatland restoration, these values vary by scenario.  I've implemented extraction code to add the choice of custom adoption scenarios to the scenario (it copies `ScenarioRecord:E271` et al. to the scenario JSON file).  I haven't checked this in yet because there is also:
 * Test failure in `verify_custom_adoption` (2).  Even with the fix above, the results are still wrong.  Investigation shows that the problem is that the _data sources themselves_ are parameterized by scenario-specific factors.  For example, the value of `"Custom Ref Adoption"!B86" is 1.5068 under the as-loaded scenario, but 1.826069903 under scenario "PDS-57p2050-PDS 2019 Plausible- Low of All".

I've stopped here because going from fixed CSV files for a custom adoption source to a parameterized value is a pretty big change; I want to discuss with @chadfrisch what the right course of action is.

TODO: create tickets for the other issues uncovered above.

**Comment by DentonGentry** [comment]
A number of the Land solutions do this. The code generator doesn't handle it, but a number of the solutions have been constructed manually. For example:

- [Conservation Agriculture](https://github.com/ProjectDrawdown/solutions/blob/9dd19670a0aad9bdfcf172b62587d216aa3ebc92/solution/conservationagriculture/__init__.py#L180)
- [Farmland Restoration](https://github.com/ProjectDrawdown/solutions/blob/9dd19670a0aad9bdfcf172b62587d216aa3ebc92/solution/farmlandrestoration/__init__.py#L160)
- [the existing Peatlands solution](https://github.com/ProjectDrawdown/solutions/blob/9dd19670a0aad9bdfcf172b62587d216aa3ebc92/solution/peatlands/__init__.py#L159)

All of those were done by hand, I never came up with a reasonable way for the code generator to handle arbitrary formulae created by the human researcher.

Subsequent updates of the solution involved re-running the code generator, then manually restoring the Custom PDS code which the code generator would overwrite, before git commit.

**Comment by denised** [comment]
Great info, @DentonGentry , thank you!

**Comment by denised** [comment]
I have submitted the first part of the fix (making the choice of adoption datasets part of the scenario definition) to the hackathon branch.  It should be available to all hackathon participants.

**Comment by denised** [comment]
The code-to-date has been checked in to develop in PR #375.  It has all the code and test fixes from the hackathon incorporated.
This model is not yet working however, so this issue remains open.

Next steps would be to do the custom parameterized scenario as outlined by Denton above.

**Comment by denised** [comment]
This is finished for the purpose of the current project push:  deleting extra scenarios in commit 3b5fd2f7 had the effect of removing all scenarios that were broken due to the missing functionality above.  We will need to come back to this when we implement secondary variables.
