### ISSUE TITLE
NEW MODEL - Recycled Glass

### ISSUE THREAD

**Issue by denised** [ProjectDrawdown/solutions#367]
Implement the recycled glass model in python
(We missed this one in the earlier list)

**Comment by cathbar** [comment]
If nobody is already working on this, I can take it.

**Comment by denised** [comment]
That would be awesome, but I recommend you wait about 1 day while I get some fixes, then you can work from the develop branch.

-- 
  Denise Draper
  ***@***.***

**Comment by cathbar** [comment]
Sounds good. Let me know when.

**Comment by denised** [comment]
....aaaand tada!
I've pulled the bug fixes in.  You will also notice some changes in how solution testing is handled --- you can be my beta tester that it works for someone other than me :-)

-- 
  Denise Draper
  ***@***.***

**Comment by denised** [comment]
@cathbar Turns out this model isn't ready for prime time yet.  There are no scenarios available.  Closing this ticket until we do have a complete model.
