### ISSUE TITLE
Implement pdoc/sphinx or similar for code documentation

### ISSUE THREAD

**Issue by denised** [ProjectDrawdown/solutions#380]
There is extensive triple-quote documentation in the code, especially the model code.  We would like to have a nicely formatted and indexed version of this documentation available for developers or researchers who are using the code.

I have an idea that that we might use the github "pages" feature to host the documentation, but totally open to other suggestions.

**Comment by yaswanthkumargothi** [comment]
Hello @denised, I would like to work on this.

**Comment by denised** [comment]
Awesome, I will assign it to you!   Let me know if I can help.

**Comment by yaswanthkumargothi** [comment]
Thanks @denised, will keep you updated on the documentation.

**Comment by denised** [comment]
This took me a lot longer to do than I expected it to, but I got there!
Our online documentation is now at [https://projectdrawdown.github.io/solutions/]
The part that has been finished is:
* The infrastructure that extracts the documentation that is already part of the code and converts that to HTML.  This is in Documentation/autodocs.
* A process that automatically runs whenever new code is checked in, so the online documentation is always kept up to date.  This is the file builddocs.sh in Documentation/autodocs, and the github actions configuration in the .github folder.

There is additional work needed to improve the content of the documentation --- I'll treat that as falling under issue #494.
