### ISSUE TITLE
Store date in scenario by updating existing records

### ISSUE THREAD

**Issue by denised** [ProjectDrawdown/solutions#400]
ScenarioRecord has a date for each scenario; we should put this into our scenarios records.
This would be a trivial addition to the extractor and the scenario record.
But to attach it to existing scenarios, instead of re-extracting them, write some code uses the ScenarioRecord stored in the expected.zip file to update them.  This would be a useful technique to have as an example.
It would also serve as a starting point for implementing #258, for example

**Comment by denised** [comment]
The date is stored in column B of the first line of each scenario in ScenarioRecord sheet.  In Expected.zip, it may appear as a datetime string, or it may appear as a floating point number like 43579.61109, which is the Excel internal representation, as described in http://www.cpearson.com/excel/datetime.htm

**Comment by johnpaulalex** [comment]
Hey Denise, I'm looking at both commercial & residential glass excels and I don't see any dates (in column B or elsewhere) on any line of any scenarios.  I do see a zero-based scenario index in column A...should I just use that?

**Comment by denised** [comment]
Thank you for this @johnpaulalex :-)
A little and a big thing at the same time.
