### ISSUE TITLE
Industry (Materials and Waste) Integration Model

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#424]
You need to complete an NDA to work on this integration.

Please review the contributing file before beginning work: https://github.com/ProjectDrawdown/solutions/blob/develop/CONTRIBUTING.md

Once the NDA is completed, access can be granted -

https://drive.google.com/drive/u/2/folders/1eFqHw8-RjQk82tJm5VdhNzte9D9hr_XA

**Comment by colleenskemp** [comment]
@denised - This is the integration that @chadfrisch flagged for us last week as a good one to start with because it is the easiest and feeds into the other integration models.

**Comment by denised** [comment]
Completed with #447
