### ISSUE TITLE
Create new tests for key results

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#425]
Description: 

This ticket is focused: Need tests that test the key results. 

Key results are results that appear at the top of the advanced control tab and summarize the output of the models)  

Acceptance criteria need to be based on key results. 

Current problem: Right now there are a lot of test failures that do not relate to key results. It is the key results that help us evaluate if we are meeting the key requirements of the project. 

It relates to creating to the following (tracked in separate tickets):
* This ticket which has been closed as duplicate: test polishing #374
* The models have to produce key results
*  The start here notebook should show off the key results. This is where you start when you use the models.

**Comment by colleenskemp** [comment]
@denised - This ticket is intended for Daniel, following the conversation we had last week. Could you add additional context and detail in this ticket for him? We can also discuss further detail during his onboarding later today.

**Comment by denised** [comment]
Sorry Colleen --- the other issue that is duplicate is #378, not #374.
