### ISSUE TITLE
Solution models in python produce key results

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#426]
Description: 

Key results are results that appear at the top of the advanced control tab and summarize the output of the models)

It is these key results that we can compare against the outputs from the excel spreadsheets and evaluate if we are meeting the key requirement of our python model producing consistent results. 

Acceptance criteria: 
All solution models produce key results.

**Comment by denised** [comment]
Issue #304 is duplicate, but has some additional information that is still useful.
