### ISSUE TITLE
test_key_results failure while test_deep_results passes

### ISSUE THREAD

**Issue by danielmk** [ProjectDrawdown/solutions#439]
Even after my PR refactoring the `get_key_results` function, there are several solutions where test_key_results fails while test_deep_results passes. Since in these cases the underlying data appears to be correct (that's what the deep test checks), `get_key_results` seems to be calculated wrongly in these scenarios. The scenarios where this is the case:

- grasslandproection
- hfc_replacement
- indigenouspeoplesland
- mangroverestoration
- peatlandrestoration
- recycledmetals
- sustainableclothing

This is based on testing I did on the 10.09.2021
I am working on this issue myself but I wanted to update others on the state of get_key_results testing.

**Comment by danielmk** [comment]
I fixed the issue in:

- grasslandprotection
- indigenouspeoplesland
- mangroverestoration
- peatlandrestoration

The problem was that the excel files for these solutions contained '-' for all financial key results. This string value causes the error because casting it to float failed. To solve the issue I wrapped the `float(expected_value)` call into a `try:` statement and upon `except:` I set the expected value to 0.0 That's consistent with what `get_key_results` returns in these cases.

**Comment by danielmk** [comment]
The issue in sustainable clothing is about decimal precision in the Python calculations compared to the expected values from the excel file.

The expected value for `net_operating_cost` is `0.0012064` but the calculated results is `0.001206403546145819`

At the default relative tolerance (1e-6) pytest.approx is False in this case.

I fixed the issue by adding absolute tolerance of 1e-7 in addition to relative tolerance.
```
rel_tol = 1e-6
abs_tol = 1e-7
pytest.approx(expected_values[0], rel=rel_tol, abs=abs_tol)
```

**Comment by danielmk** [comment]
The issue in hfc_replacement was that some of the financial parameters were causing errors in the financial key results (values of 0 that should never be 0 by assertion).

I pushed changes to my current PR that check for such bad parameters and give 0.0 for the affected key_results.

hfc_replacement passes key_result tests now.

**Comment by danielmk** [comment]
Found the issue with recycledmetals. This is the only solution where the interval to calculate `net_operating_savings` and `lifetime_operating_savings` and the total emissions is from 2018-2050. Any other scenario it is from 2020-2050.
So I'll rewrite the key_results calculations to use self.ac.report_start_year and self.ac.report_end_year instead of hardcoded years.
This is better form anyway.

**Comment by danielmk** [comment]
The last solution that is relevant for this issue is sustainableclothing

This is the error:
```
E                   AssertionError: EXPECTED: 21.32340145 ± 2.1e-05
E                   ACTUAL: 21.03598432004792
E                    IN cumulative_emissions_reduced
```

There is something really weird going on here, maybe you have an idea @denised 

This error occurs during testing of scenario 1 (the second) which according to the testing output is called `Checking scenario 1: PDS2-32p2050-Dec20`
However, when I create `PDS2` in jupyter it creates `'PDS2-32p2050-Jan2021'` instead.
When I then calculate the key_results, I get the exptected value: `21.323401451348694`

Looking at the .zip file for `'PDS2-32p2050-Jan2021'` confirms 21.32340145 is the correct expected value for this scenario.

So somehow the test suite loads `'PDS2-32p2050-Dec20'` and calculates the key results for it but then expects the values from 'PDS2-32p2050-Jan2021'`.

Any ideas how to fix this? I've been unable to trace it further.

**Comment by denised** [comment]
There are *two* PDS2 scenarios for sustainable clothing.  The loop in key_results_tester and deep_results_tester goes through all the scenarios, so it tests both PDS2 scenarios.  To test this one manually, you would need to give the actual name of the other PDS2 scenario in full:

factory.load_scenario("sustainableclothing", "PDS2-32p2050-Dec20")

-- 
  Denise Draper
  ***@***.***



On Mon, Sep 13, 2021, at 8:14 AM, Daniel Müller-Komorowska wrote:
> 
> 
> The last solution that is relevant for this issue is sustainableclothing
> 
> This is the error:
> 
> `E                   AssertionError: EXPECTED: 21.32340145 ± 2.1e-05
> E                   ACTUAL: 21.03598432004792
> E                    IN cumulative_emissions_reduced
`

**Comment by danielmk** [comment]
Thanks @denised , I didn't actually know the test goes through all scenarios, I thought just the ones it finds for PDS1, PDS2 and PDS3.

However, I am still not able to trace this problem. It doesn't make sense to me that the key results would fail while the deep testing passes. Since this issue got unwieldy I think I will close it and move on to other testing failures. I might create a separate issue for sustainableclothing at some point.
