### ISSUE TITLE
Fix of FaIR Deprecation Warning

### ISSUE THREAD

**Issue by denised** [ProjectDrawdown/solutions#443]
We're getting deprecation warnings from FaIR:
```
solution/sustainableclothing/tests/test_sustainableclothing.py::test_loader
  C:\ProgramData\Miniconda3\envs\foo\lib\site-packages\fair\RCPs\rcp3pd.py:4: DeprecationWarning: name rcp3pd will be deprecated in FaIR 2.0. Please use rcp26.
    warnings.warn('name rcp3pd will be deprecated in FaIR 2.0. Please use rcp26.',

solution/sustainableclothing/tests/test_sustainableclothing.py::test_loader
  C:\ProgramData\Miniconda3\envs\foo\lib\site-packages\fair\RCPs\rcp6.py:4: DeprecationWarning: name rcp6 will be deprecated in FaIR 2.0. Please use rcp60.
    warnings.warn('name rcp6 will be deprecated in FaIR 2.0. Please use rcp60.',
```

We should update.  @krcolbert indicated this should not be a problem.

**Comment by gerald-scharitzer** [comment]
rcp3pd and rcp6 are used by [model/co2calcs.py](https://github.com/ProjectDrawdown/solutions/blob/1523df254841ae9b33860497b9cc328ca629d49b/model/co2calcs.py#L14) and thus affect the model. Does this still qualify as "good first issue"?

**Comment by gerald-scharitzer** [comment]
The old and new names refer to the same things in [fair.RCPs](https://github.com/OMS-NetZero/FAIR/blob/1d89c23096ae583c06581b1a2e1cb59f1aa44e13/fair/RCPs/__init__.py#L21), so this is just about renaming them on our side.

**Comment by denised** [comment]
Doing the research to figure that out is most of the work for this ticket, I expect :-)
Feel free to make the fix, if you wish, and thank you.

-- 
  Denise Draper
  ***@***.***

**Comment by gerald-scharitzer** [comment]
How do you get those depreciation warnings?
I cannot reproduce them with pytest.
```
(pd-dev) $ pytest model/tests/test_co2calcs.py 
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
Date: 2021-11-14 00:28:09.477877
Git: v0.24.1-2-g1523df25 (develop)
rootdir: ***, configfile: tox.ini
collected 32 items                                                                                                                                                                                        

model/tests/test_co2calcs.py ...............................s                                                                                                                                       [100%]

====================================================================================== 31 passed, 1 skipped in 2.19s ======================================================================================
(pd-dev) $ pytest solution/sustainableclothing/
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
Date: 2021-11-14 00:28:33.405427
Git: v0.24.1-2-g1523df25 (develop)
rootdir: ***, configfile: tox.ini
collected 3 items                                                                                                                                                                                         

solution/sustainableclothing/tests/test_sustainableclothing.py ...                                                                                                                                  [100%]

============================================================================================ 3 passed in 7.26s ============================================================================================
```

**Comment by denised** [comment]
Ah, you have to remove the filterwarnings from tox.ini, where I had put it because it made too much noise in the tests:
    ignore:.*will be deprecated in FaIR 2.0.*:DeprecationWarning

-- 
  Denise Draper
  ***@***.***



On Sat, Nov 13, 2021, at 3:39 PM, Gerald Scharitzer wrote:
> 
> 
> 
> How do you get those depreciation warnings?
> I cannot reproduce them with pytest.
> 
> `(pd-dev) $ pytest model/tests/test_co2calcs.py 
> =========================================================================================== test session starts ===========================================================================================
> platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
> Date: 2021-11-14 00:28:09.477877
> Git: v0.24.1-2-g1523df25 (develop)
> rootdir: ***, configfile: tox.ini
> collected 32 items                                                                                                                                                                                        
> 
> model/tests/test_co2calcs.py ...............................s                                                                                                                                       [100%]
> 
> ====================================================================================== 31 passed, 1 skipped in 2.19s ======================================================================================
> (pd-dev) $ pytest solution/sustainableclothing/
> =========================================================================================== test session starts ===========================================================================================
> platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
> Date: 2021-11-14 00:28:33.405427
> Git: v0.24.1-2-g1523df25 (develop)
> rootdir: ***, configfile: tox.ini
> collected 3 items                                                                                                                                                                                         
> 
> solution/sustainableclothing/tests/test_sustainableclothing.py ...                                                                                                                                  [100%]
> 
> ============================================================================================ 3 passed in 7.26s ============================================================================================
`

**Comment by gerald-scharitzer** [comment]
In my case, the depreciation warnings came from [fair-1.6.3](https://github.com/OMS-NetZero/FAIR/blob/v1.6.3/fair/RCPs/rcp3pd.py). With [fair-1.6.4](https://github.com/OMS-NetZero/FAIR/blob/e1d7d11d67d81780b9e8bed5af664bcf9218c9d5/fair/RCPs/__init__.py#L21) they are gone. Next, I will try to resolve this via "fair>=1.6.4" in [environment.yml](https://github.com/ProjectDrawdown/solutions/blob/1523df254841ae9b33860497b9cc328ca629d49b/environment.yml#L14) and [requirements.txt](https://github.com/ProjectDrawdown/solutions/blob/develop/requirements.txt).

**Comment by gerald-scharitzer** [comment]
`fair>=1.6.4` resolves this, but requires `conda env update -f environment.yml --prune` to become effective for existing environments. Therefore, I will update the names in [model/co2calcs.py](https://github.com/ProjectDrawdown/solutions/blob/1523df254841ae9b33860497b9cc328ca629d49b/model/co2calcs.py#L14) as well for smooth syncing.

**Comment by gerald-scharitzer** [comment]
Pull request #511 submitted

**Comment by denised** [comment]
Completed by @gerald-scharitzer with PR #511
