### ISSUE TITLE
Static code analysis

### ISSUE THREAD

**Issue by avishayp** [ProjectDrawdown/solutions#47]
Suggestion:

1.  Do a pylint-driven code cleaning
2.  Add `pylint` to the workflow

I've started with [1], but I already see that fixing the issues raised by `pylint` requires a deeper level of familiarity with the codebase. So some help will be needed.

If that's ok, I'll submit a PR to clean unused vars, unused imports, redundant semicolons etc.

**Comment by DentonGentry** [comment]
Sure, pylint would be great. I wish we'd done it sooner, just didn't get it done.

We started with the Google Python coding style (2 space indent) and later reformatted to be closer to PEP8. There may be a few files left which are 2 space indent, and can be reformatted to 4 space.

**Comment by avishayp** [comment]
Let's handle inconsistent indent in separate PR it'll create a huge difficult to review diff for you.

**Comment by avishayp** [comment]
To update: am working on it. Analysis is not reliable enough to be blindly trusted, I've broken some tests removing imports or variables marked as unused by pylint. Which also makes me reconsider adding pylint to the CI workflow.

**Comment by DentonGentry** [comment]
Certainly, every time I've tried to use pylint on nontrivial amounts of code it has involved #pylint comments to resolve occasional inexplicable behaviors. Nonetheless I've found pylint to be valuable for finding real problems which otherwise would not have been noticed until much later, I'd encourage the effort spent on it.

**Comment by tpltnt** [comment]
Is issue is very broad. Maybe it should be split into smaller, well-defined PRs with a definition of done for each. (i.e. one for indentation, one for another class of issues, one for adding pylint explicity to the CI pipeline)

**Comment by avishayp** [comment]
The DoD of this issue:

 * Ad-hoc discovery and fix of some low-hanging bugs (arguably addressed in #53 )
 * Converge to an agreed-upon set of pylint W/E/F flags which can be put into workflow without creating too much noise (or decide against that)

The bikeshedding part is under #48

**Comment by avishayp** [comment]
By stated DoD #61 should close this.
