### ISSUE TITLE
Fix inconsistent indentation

### ISSUE THREAD

**Issue by avishayp** [ProjectDrawdown/solutions#48]
pylint tells me the autogenerated files are mostly using 2-space ident.
This issue is to reformat all files to 4-space indentation.

**Comment by avishayp** [comment]
@DentonGentry considering this will be practically unreviewable, is there anything I could could test on top of the test suite to be confident the reformat didn't break anything?

**Comment by DentonGentry** [comment]
I'd recommend to run the Jupyter notebook, we don't (yet) have automated tests that the notebook still works.

I'd request not to reformat the autogenerated files in solution/*/__init__.py, as we're very soon (within days) going to begin importing new versions of the solutions which would generate new files with two space indent. If you fix the rest of the tree, I'll redo tools/solution_xls_extract.py to use four space indent before we begin importing the new files.

**Comment by jonathan-s** [comment]
May I suggest the library black for formatting? https://github.com/psf/black

**Comment by DentonGentry** [comment]
While I understand the purpose of something like https://github.com/psf/black, in the same general idea as gofmt for eliminating bikeshedding about whitespace, I'm not all that enthused about adopting something like that just yet as the arbiter of code style.
