### ISSUE TITLE
Update the models required for integrations

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#489]
Which of the incomplete models are MUST HAVEs for the end of October delivery? The ones that support integrations.

Please focus on these. 
@denised to share list in ticket or ID in PD Solution spreadsheet
https://docs.google.com/spreadsheets/d/1UyDXHyItk0aN36Q7w6oHkXHQI4t9FLxZhvAFD2aDymg/edit?pli=1#gid=444298670

**Comment by denised** [comment]
Thanks @danielmk --- removing you from assignee list (for now :-)

**Comment by denised** [comment]
Closing this issue since the priority required for integrations has passed.
