### ISSUE TITLE
Selenium tests for Jupyter

### ISSUE THREAD

**Issue by DentonGentry** [ProjectDrawdown/solutions#5]
Very little of the code used in the Jupyter UI is embedded within the notebook file itself. Most of the code is in separate Python files, with some very basic unit tests. Nonetheless, test coverage is not great.

We would benefit greatly from automated UI tests like Selenium, or a similar framework. Setting up such tests would not require extensive familiarity with the Drawdown codebase or models, it would mostly require familiarity with construction of such tests.

Even if we deprecate the Jupyter notebook UI, we'd bring along the test framework and set up tests for the new UI.

**Comment by jonathan-s** [comment]
Some notes on testing jupyter notebooks -> https://blog.thedataincubator.com/2016/06/testing-jupyter-notebooks/ 

That is to say using selenium may not be the best approach. Unless it's purely UI that is being tested (I still haven't read much of the project, so I may be completely wrong here, but at first glance it sounds like pure unittest would be better than using selenium).

**Comment by DentonGentry** [comment]
nbconvert does work to render the Overview page of the notebook, both the Voilà  version and the Jupyterlab version:

`jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=60 --output rendered ./Drawdown.ipynb`

`jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=60 --output rendered ./Drawdown.ipynb`

This is what the rendered Overview page would look like.

<img width="749" alt="Screen Shot 2020-02-26 at 7 22 03 PM" src="https://user-images.githubusercontent.com/1140756/75409348-540e8880-58cd-11ea-8f05-6954f0d1273c.png">

Clicking the checkbox triggers the rest of the tabs to be run: https://youtu.be/RAQSnhm_tS4

I think that testing the functionality past the Overview page would require a UI testing framework rather than nbconvert alone.

**Comment by 4dahalibut** [comment]
I'll check this one out.

**Comment by DentonGentry** [comment]
https://github.com/ProjectDrawdown/solutions/pull/80
https://github.com/ProjectDrawdown/solutions/pull/86
https://github.com/ProjectDrawdown/solutions/pull/87

Calling this one done.
