### ISSUE TITLE
Set up cronjobs for model health

### ISSUE THREAD

**Issue by DentonGentry** [ProjectDrawdown/solutions#6]
There is a dashboard of the health of the solution models constructed in Jupyterlab in [ModelHealth.ipynb](https://github.com/ProjectDrawdown/solutions/blob/master/ModelHealth.ipynb). It reads several CSV files in data/health with various factors about the health of the model. These CSV files are written by two tools which were written at different times by different people, and are currently run manually whenever the developers remember to do so. There is a need to rationalize and automate these tools.

<img width="276" alt="ModelHealth" src="https://user-images.githubusercontent.com/1140756/74085313-bee64580-4a2c-11ea-998e-6761d8c96a80.png">

[tools/health/survey.py](https://github.com/ProjectDrawdown/solutions/blob/master/tools/health/survey.py) writes to a new data/health/survey_*.csv file which it prints to stdout. It was expected that an automated pipeline would conduct a few sanity checks before moving the new file into [data/health/survey.csv](https://github.com/ProjectDrawdown/solutions/blob/master/data/health/survey.csv) and committing it to the repository.

[tools/health/landsurvey.py](https://github.com/ProjectDrawdown/solutions/blob/master/tools/health/landsurvey.py) updates data/health/landsurvey.csv directly. We are inconsistent in this way.

The steps for this task would be:
1. Rationalize how the two scripts work, whether to write to a new file or to update the existing file.  

    As the next step would check out a new workspace, writing to a new file seems unnecessary now. [tools/health/survey.py](https://github.com/ProjectDrawdown/solutions/blob/master/tools/health/survey.py) could overwrite [data/health/survey.csv](https://github.com/ProjectDrawdown/solutions/blob/master/data/health/survey.csv).

1. As an additional step in continuous integration, write a Github Task to run the two scripts and perform a sanity check that they can be read in.

1. Bonus step: figure out a way to host the dashboard online, not a locally run Notebook, which likely means reimplementing it as something other than a Jupyter notebook. Ideally, this would use something like Github Pages not a separately hosted service we have to look after.

**Comment by 4dahalibut** [comment]
Hey I'm thinking of working on this tonight

**Comment by DentonGentry** [comment]
https://github.com/ProjectDrawdown/solutions/pull/79
https://github.com/ProjectDrawdown/solutions/pull/83
https://github.com/ProjectDrawdown/solutions/pull/84
