### ISSUE TITLE
Optimize solution+scenario initialization

### ISSUE THREAD

**Issue by DentonGentry** [ProjectDrawdown/solutions#8]
In the Project Drawdown terminology:

- solution is a way to draw down greenhouse gasses such as building Offshore Wind generation or changing practices to use Regenerative Agriculture.
- scenario is a set of inputs and assumptions to the model of the solution, from optimistic to pessimistic

In this software implementation, solutions are Python modules like [solution/offshorewind](https://github.com/ProjectDrawdown/solutions/tree/master/solution/offshorewind), and scenarios are inputs passed to the solution constructor. Typical Drawdown solutions have three or more scenarios, which would turn into three solution object allocations.

Instantiating a solution object takes roughly one second. We avoid instantiating new objects, preferring to generate results offline to be saved as data files. If the objects could be allocated more cheaply, we'd use them more interactively.

[tests/test_solutions.py](https://github.com/ProjectDrawdown/solutions/blob/master/tests/test_solutions.py) and [tests/test_excel_integration.py](https://github.com/ProjectDrawdown/solutions/blob/master/tests/test_excel_integration.py) both allocate all solutions and all scenarios, and would be useful for profiling. Based on profiling, we can determine what to work on.

Some notes:
1. As a design philosophy, model components like the [TAM](https://github.com/ProjectDrawdown/solutions/blob/master/model/tam.py), [adoptiondata](https://github.com/ProjectDrawdown/solutions/blob/master/model/adoptiondata.py), and [co2calcs](https://github.com/ProjectDrawdown/solutions/blob/master/model/co2calcs.py) are intended to be immutable. They take their inputs at initialization. Methods only take selector arguments like what region to return, or whether to return the mean/low/high.  
This allowed an earlier optimization, a [metaclass_cache.py](https://github.com/ProjectDrawdown/solutions/blob/master/model/metaclass_cache.py) to share the TAM between scenarios within a solution.  

1. In most cases, operations on data are handled using built-in Pandas DataFrame methods which should call into the numpy native implementations. However there are a few places in the codebase which use DataFrame.apply(), which means that interpreted Python code is processing every datapoint. These places should be re-examined, particularly if they show up anywhere in profiling.

1. Most uses of apply() were written when the author had relatively little experience with Pandas, and can possibly be re-implemented using built-in functions with a little effort.

**Comment by klemag** [comment]
Hi @DentonGentry , happy to give this one a go

**Comment by DentonGentry** [comment]
I think @klemag addressed this issue with https://github.com/ProjectDrawdown/solutions/pull/97, with extremely good performance gains in running the models.
